name: Sync GitHub to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify PAT Exists
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          if [ -z "$AZURE_DEVOPS_PAT" ]; then
            echo "PAT is empty"
            exit 1
          else
            echo "PAT found"
          fi

      - name: Verify Azure Repo Access
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git ls-remote https://git:${AZURE_DEVOPS_PAT}@dev.azure.com/manoonam1729/ManoDeployment/_git/ManoDeployment

      - name: Push to Azure Repos
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git push https://git:${AZURE_DEVOPS_PAT}@dev.azure.com/manoonam1729/ManoDeployment/_git/ManoDeployment HEAD:main
