name: Sync GitHub to Azure Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify Secret Exists
        env: 
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          if [ -z "$AZURE_DEVOPS_PAT" ]; then
            echo "PAT is empty"
            exit 1
          else
            echo "PAT found"
          fi

      - name: Add Azure Remote
        env: 
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          git remote add azure https://${AZURE_DEVOPS_PAT }@dev.azure.com/manoonam1729/ManoDeployment/_git/ManoDeployment

      - name: Push to Azure Repos
        run: |
          git push azure main
